name: github pages

on:
  push:
    branches:
      - master  # Set a branch that will trigger a deployment

jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod
          
      - name: setup-node
        uses: actions/setup-node@v1
        with:
          node-version: '16'
          
      - name: install-and-build
        run: |
          npm install
          npm run build
          
      - name: hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'

      - name: hugo-gene-docs
        run: hugo --minify
